from typing import List, Optional
from pydantic import BaseModel, Field
from veadk import Agent
from veadk.tools.builtin_tools.web_search import web_search


# 1. Define Data Models
class ResearchDecision(BaseModel):
    nextSearchTopic: Optional[str] = Field(description="The next topic to search for.")
    shouldContinue: bool = Field(
        description="Whether to continue searching. Set to False if sufficient information has been gathered."
    )


# 2. Define Agents

# Research Decider (Corresponds to LLM Node)
research_decider = Agent(
    name="ResearchDecider",
    description="Analyzes current findings and decides on the next search topic.",
    instruction="""You are a research agent responsible for investigating topics.
    Based on the user's query and current findings, determine what to search for next.
    If you have gathered sufficient information to answer the original query comprehensively, set shouldContinue to False.
    Otherwise, provide a specific nextSearchTopic.
    
    Output in JSON format matching the schema.
    """,
    model_extra_config={"response_format": ResearchDecision, "temperature": 0.7},
    model="gpt-4o",
)

# Report Generator (Corresponds to Reasoning Model)
report_generator = Agent(
    name="ReportGenerator",
    description="Generates a comprehensive report based on research findings.",
    instruction="""Summarize the investigation results.
    Provide important insights, conclusions, and remaining uncertainties.
    Cite sources appropriately.
    The summary should be very comprehensive and detailed.
    Output in Markdown format.
    """,
    model="deepseek-reasoner",
    model_extra_config={"temperature": 0.7},
)

# 3. Define the Workflow Logic as a Tool


def deep_research(query: str, depth: int = 3) -> str:
    """
    Performs deep research on a given query with a specified depth.

    Args:
        query (str): The research topic or question.
        depth (int): The maximum number of search iterations. Defaults to 3.

    Returns:
        str: A comprehensive research report.
    """
    topics: List[str] = []
    findings: List[str] = []

    current_depth = 0

    # Loop corresponds to Dify Iteration Node
    while current_depth < depth:
        # Construct context for the decider
        context_str = f"## Topic\n{query}\n\n## Current Findings\n"
        for i, f in enumerate(findings):
            context_str += f"Finding {i + 1}: {f}\n"
        context_str += "\n## Searched Topics\n"
        for t in topics:
            context_str += f"- {t}\n"

        # Call Research Decider
        # agent.run() is assumed to return the parsed ResearchDecision object
        response = research_decider.run(context_str)

        # Handle potential wrapper or direct object
        # Assuming response is the object or has the data
        if hasattr(response, "shouldContinue"):
            decision = response
        else:
            # Fallback if response is a string or wrapper (adjust based on actual VeADK runtime)
            # This part assumes VeADK returns the Pydantic model instance
            decision = response

        if not decision.shouldContinue:
            break

        if decision.nextSearchTopic:
            topics.append(decision.nextSearchTopic)

            # Execute Search (Corresponds to Tavily Search Node)
            # Using builtin web_search
            try:
                search_res = web_search(query=decision.nextSearchTopic)
                findings.append(search_res)
            except Exception as e:
                findings.append(
                    f"Search failed for {decision.nextSearchTopic}: {str(e)}"
                )

        current_depth += 1

    # Generate Report (Corresponds to Reasoning Model Node)
    final_context = f"## Topic\n{query}\n\n# Findings\n"
    for i, f in enumerate(findings):
        final_context += f"Finding {i + 1}: {f}\n"

    report = report_generator.run(final_context)

    return str(report)


# 4. Root Agent
# The root agent exposes the deep_research tool to the user.
# This allows the user to say "Research X with depth Y" or just "Research X".

root_agent = Agent(
    name="DeepResearchAgent",
    description="A deep research agent that iteratively searches and summarizes information.",
    instruction="""You are a deep research assistant. 
    When a user asks to research a topic, use the deep_research tool.
    You can specify the depth if the user requests it, otherwise default to 3.
    Return the report generated by the tool directly to the user.
    """,
    tools=[deep_research],
)
