name:                     # 中文名称（255字符）
name_en:                  # 英文名称（255字符）
description:              # 简介（10-60字）
details:                  # 详细介绍（10-400字）
tags:
  # 行业场景标签（金融、汽车、泛互、医疗、零售、广告营销、能源电力、信息技术服务、教育、工业、制造等）
  industry:               
  from:                   # 来源标签（volcengine | community）
  framework:              # 代码框架
  language:               # 开发语言
  tech:                   # 技术标签（可选），最多 5 个
    -
type:                     # 类型，可选项为 tutorial | application
scenarios:                 # 应用场景（2-6个），type 为 application 时必填
  - name:                 # 应用场景名称（2-15字）
    desc:                 # 应用场景描述（10-20字）
  - name:
    desc:
prompts:                  # Prompt 样例
  - text:                 # Prompt 文本（简洁精炼）
    resource_url:         # 必要的多模态数据 URL（公网可访问）
  - prompt:
    resource_url:
envs:                     # 所需的环境变量（用于第三方依赖服务）
  - name:                 # 环境变量中文名
    key:                  # 环境变量名
    url:                  # 引导链接
components:               # Agentkit 依赖服务
  - type:               # 服务类型，可选项为 tool | knowledgebase | memory
    # 对应产品（不区分大小写）
    # tool: AIO_Sandbox | Skills_Sandbox
    # knowledgebase: VikingKnowledge
    # memory: VikingMem | Mem0
    product:
models:                   # 涉及到的具体模型列表
    - doubao-seed-1-8-251215
